# v1.1.3
name: Theme CI
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'build/**'
      - 'README.md'
      - 'LICENSE'
    branches:
      [master, dev]
  pull_request_target:
    branches:
      [master, dev]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'build/**'
      - 'README.md'
      - 'LICENSE'

jobs:
  ci:
    runs-on: ubuntu-latest
    env: 
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      BLOB_SAS: ${{ secrets.BLOB_TOKEN }}
      VERSION_SUFFIX: ""

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3

    - name: Get Image Version
      uses: VirtoCommerce/vc-github-actions/get-image-version@master
      id: image

    - name: Set VERSION_SUFFIX variable
      run: |
        if [ '${{ github.event_name }}' = 'workflow_dispatch' ]; then
          echo "VERSION_SUFFIX=${{ steps.image.outputs.fullSuffix }}" >> $GITHUB_ENV
        else
          echo "VERSION_SUFFIX=${{ steps.image.outputs.suffix }}" >> $GITHUB_ENV
        fi;

    - name: Get changelog
      id: changelog
      uses: VirtoCommerce/vc-github-actions/changelog-generator@master

    - name: SonarCloud Scan
      uses: VirtoCommerce/vc-github-actions/sonar-theme@VCI-152
      with:
        projectVersion: ${{ steps.image.outputs.fullVersion }}
        sonarToken: ${{secrets.SONAR_TOKEN}}

    - name: Build
      if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.event_name == 'workflow_dispatch' }}
      id: build
      uses: VirtoCommerce/vc-github-actions/build-theme@master
      with:
        versionSuffix: ${{ env.VERSION_SUFFIX }}

    - name: Publish
      if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || (github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/master')}}
      id: publish
      uses: VirtoCommerce/vc-github-actions/publish-theme@master
      with:
        artifactPath: ${{ steps.build.outputs.artifactPath }}
        artifactName: ${{ steps.build.outputs.artifactName }}

    - name: Create Release
      if: ${{ github.ref == 'refs/heads/master' }}
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.image.outputs.prefix }}
        release_name: ${{ steps.image.outputs.prefix }}
        draft: false
        prerelease: false
        body: ${{ steps.changelog.outputs.changelog }}

    - name: Upload Release Asset
      if: ${{ github.ref == 'refs/heads/master' }}
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.build.outputs.artifactPath }}
        asset_name: ${{ steps.build.outputs.artifactName }}
        asset_content_type: application/zip